#[path = "../../../makepad/draw/src/text/color.rs"]
pub mod color;
#[path = "../../../makepad/draw/src/text/font.rs"]
pub mod font;
#[path = "../../../makepad/draw/src/text/font_atlas.rs"]
pub mod font_atlas;
#[path = "../../../makepad/draw/src/text/font_face.rs"]
pub mod font_face;
#[path = "../../../makepad/draw/src/text/font_family.rs"]
pub mod font_family;
#[path = "../../../makepad/draw/src/text/geom.rs"]
pub mod geom;
#[path = "../../../makepad/draw/src/text/glyph_outline.rs"]
pub mod glyph_outline;
#[path = "../../../makepad/draw/src/text/glyph_raster_image.rs"]
pub mod glyph_raster_image;
#[path = "../../../makepad/draw/src/text/image.rs"]
pub mod image;
#[path = "../../../makepad/draw/src/text/intern.rs"]
pub mod intern;
#[path = "../../../makepad/draw/src/text/layouter.rs"]
pub mod layouter;
#[path = "../../../makepad/draw/src/text/loader.rs"]
pub mod loader;
#[path = "../../../makepad/draw/src/text/msdfer.rs"]
pub mod msdfer;
#[path = "../../../makepad/draw/src/text/num.rs"]
pub mod num;
#[path = "../../../makepad/draw/src/text/rasterizer.rs"]
pub mod rasterizer;
#[path = "../../../makepad/draw/src/text/sdfer.rs"]
pub mod sdfer;
#[path = "../../../makepad/draw/src/text/selection.rs"]
pub mod selection;
#[path = "../../../makepad/draw/src/text/shaper.rs"]
pub mod shaper;
#[path = "../../../makepad/draw/src/text/slice.rs"]
pub mod slice;
#[path = "../../../makepad/draw/src/text/substr.rs"]
pub mod substr;
