[package]
name = "cargo-makepad"
version = "1.0.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2021"
description = "Makepad cargo extension (browser build only)"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/makepad/makepad/"
repository = "https://github.com/makepad/makepad/"

[dependencies]
makepad-shell = { path = "../../libs/shell", version = "1.0.0" }
makepad-wasm-strip = { path = "../../libs/wasm_strip", version = "1.0.0" }
wasm-bindgen-cli-support = "=0.2.128"
