//! Extracts the JS message bridge from a built wasm module.
//!
//! The wasm exports the bridge source and its fingerprint; running those
//! exports in a host interpreter with every import stubbed proves the source
//! depends on nothing but the message definitions compiled into the module.

use wasmi::{Engine, Extern, ExternType, Linker, Module, Nullable, Ref, Store, Val};

pub struct BridgeSource {
    pub source: String,
    pub hash: u64,
}

pub fn extract_bridge(wasm: &[u8]) -> Result<BridgeSource, String> {
    let engine = Engine::default();
    let module = Module::new(&engine, wasm).map_err(|e| format!("invalid wasm: {e}"))?;
    let mut store = Store::new(&engine, ());
    let mut linker = Linker::new(&engine);

    for import in module.imports() {
        let module_name = import.module();
        let name = import.name();
        match import.ty() {
            ExternType::Func(ty) => {
                let label = format!("{module_name}::{name}");
                linker
                    .func_new(module_name, name, ty.clone(), move |_, _, _| {
                        Err(wasmi::Error::new(format!(
                            "bridge extraction must not call host import {label}"
                        )))
                    })
                    .map_err(|e| e.to_string())?;
            }
            ExternType::Memory(ty) => {
                let memory = wasmi::Memory::new(&mut store, *ty).map_err(|e| e.to_string())?;
                linker
                    .define(module_name, name, Extern::Memory(memory))
                    .map_err(|e| e.to_string())?;
            }
            ExternType::Table(ty) => {
                let table = wasmi::Table::new(&mut store, *ty, Ref::Func(Nullable::Null))
                    .map_err(|e| e.to_string())?;
                linker
                    .define(module_name, name, Extern::Table(table))
                    .map_err(|e| e.to_string())?;
            }
            ExternType::Global(ty) => {
                let init = Val::default_for_ty(ty.content());
                let global = wasmi::Global::new(&mut store, init, ty.mutability());
                linker
                    .define(module_name, name, Extern::Global(global))
                    .map_err(|e| e.to_string())?;
            }
        }
    }

    let instance = linker
        .instantiate_and_start(&mut store, &module)
        .map_err(|e| format!("instantiate: {e}"))?;
    let memory = instance
        .get_memory(&store, "memory")
        .ok_or("wasm exports no memory")?;
    let source_fn = instance
        .get_typed_func::<(), u32>(&store, "wasm_js_message_bridge_source")
        .map_err(|e| format!("wasm_js_message_bridge_source: {e}"))?;
    let hash_fn = instance
        .get_typed_func::<(), u64>(&store, "wasm_js_message_bridge_hash")
        .map_err(|e| format!("wasm_js_message_bridge_hash: {e}"))?;
    let free_fn = instance
        .get_typed_func::<u32, ()>(&store, "wasm_msg_free")
        .map_err(|e| format!("wasm_msg_free: {e}"))?;

    let ptr = source_fn
        .call(&mut store, ())
        .map_err(|e| format!("bridge source export trapped: {e}"))?;
    let source = read_message_string(memory.data(&store), ptr)?;
    free_fn
        .call(&mut store, ptr)
        .map_err(|e| format!("wasm_msg_free trapped: {e}"))?;
    let hash = hash_fn
        .call(&mut store, ())
        .map_err(|e| format!("bridge hash export trapped: {e}"))?;
    Ok(BridgeSource { source, hash })
}

/// Reads the single string a `FromWasmMsg` carries: a u64 header (capacity,
/// length) followed by a u32 char count and one u32 per char.
fn read_message_string(data: &[u8], ptr: u32) -> Result<String, String> {
    let read_u32 = |offset: usize| -> Result<u32, String> {
        let bytes = data
            .get(offset..offset + 4)
            .ok_or_else(|| format!("message read out of bounds at {offset}"))?;
        Ok(u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]))
    };
    let mut offset = ptr as usize + 8;
    let len = read_u32(offset)? as usize;
    offset += 4;
    let mut out = String::with_capacity(len);
    for _ in 0..len {
        let code = read_u32(offset)?;
        offset += 4;
        out.push(char::from_u32(code).ok_or_else(|| format!("invalid char {code}"))?);
    }
    Ok(out)
}

/// The ES module shipped next to the wasm; the hash lets the loader refuse to
/// drive a wasm with a bridge generated from different message definitions.
pub fn render_bridge_module(source: &str, hash: u64) -> String {
    format!(
        "// Generated by `mbx xtask build-web` from the wasm message definitions. Do not edit.\n\
         export const SCHEMA_HASH = \"{hash}\";\n\
         export function create_message_classes(ToWasmMsg, FromWasmMsg) {{\n{source}\n}}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn module_exports_hash_and_factory_with_the_source_verbatim() {
        let source = "return {\nToWasmMsg:class extends ToWasmMsg{\n},\nFromWasmMsg:class extends FromWasmMsg{\n}\n}";
        let module = render_bridge_module(source, 0x1234_5678_9abc_def0);
        assert!(module.contains("export const SCHEMA_HASH = \"1311768467463790320\";"));
        assert!(module.contains("export function create_message_classes(ToWasmMsg, FromWasmMsg) {"));
        assert!(module.contains(source));
        assert!(!module.contains("new Function"));
    }

    #[test]
    fn message_string_is_decoded_from_the_from_wasm_layout() {
        let mut data = vec![0u8; 16];
        let text = "ab";
        data.extend_from_slice(&(text.len() as u32).to_le_bytes());
        for c in text.chars() {
            data.extend_from_slice(&(c as u32).to_le_bytes());
        }
        assert_eq!(read_message_string(&data, 8).unwrap(), "ab");
        assert!(read_message_string(&data, 100).is_err());
    }
}
